// ───────────────────── {{MARCA}} · diagnóstico del expediente (Piloto 7) ─────────────────────
// Chequeo de salud del expediente: qué puede salir mal, qué oportunidad hay y qué dato falta, en 30 segundos.
// Todo se deriva de x, R = calcular(x), estrategia(x), particion(x, R) y los trámites; se reutilizan las alertas
// del motor (R.isd.alertas, R.plus[].r.alertas, R.isd.pendientes) reformuladas y sin duplicar.
// API: diagnostico(x, R) → { score, nivel, items, areas } · tDiagnostico(x, R) → HTML de la pestaña ·
//      dgResumen(x, R) → tarjeta compacta para el Resumen · dgParaInforme(x, R) → bloques para pdf.js.
const DG_AREAS = [["plazos", "Plazos", "Plazos"], ["impuestos", "Impuestos", "Impuestos"], ["reparto", "Reparto y legítimas", "Reparto"], ["datos", "Datos del expediente", "Datos"], ["tramites", "Trámites", "Trámites"], ["docs", "Documentación", "Documentos"]];
const DG_PESO = { 3: 15, 2: 7, 1: 3 };
const DG_NIVEL = { bien: "Bien", atencion: "Atención", riesgo: "Riesgo" };
const DG_I_DEMORA = 0.040625; // interés de demora 2026 (LPGE), el mismo que usa Estrategia fiscal
const dgHoy = () => hoy();
const dgDias = (a, b) => (a && b ? dias(a, b) : 0);
function dgMeses(f, n) { const d = new Date(f + "T12:00:00"); const dia = d.getDate(); d.setMonth(d.getMonth() + n); if (d.getDate() < dia) d.setDate(0); return d.toISOString().slice(0, 10); }
const dgMesesEntre = (a, b) => { const A = new Date(a + "T12:00:00"), B = new Date(b + "T12:00:00"); let m = (B.getFullYear() - A.getFullYear()) * 12 + B.getMonth() - A.getMonth(); if (B.getDate() < A.getDate()) m--; return Math.max(0, m); };
const dgPlural = (n, s, p) => `${n} ${n === 1 ? s : p || s + "s"}`;
const dgInm = (b) => b.tipo === "vivienda" || b.tipo === "inmueble";
const dgNombreBien = (b) => b.descripcion || (TIPO_BIEN[b.tipo] ? TIPO_BIEN[b.tipo][0] : "Bien");
const dgNombre = (p) => p.nombre || (RELACIONES[p.relacion] ? RELACIONES[p.relacion].label : "Persona");
const dgEdadVale = (p) => p.edad !== "" && p.edad != null && !isNaN(num(p.edad));
const dgR2 = (v) => Math.round((v + Number.EPSILON) * 100) / 100;
// Recargo por presentación fuera de plazo sin requerimiento (art. 27 LGT): 1 % + 1 % por mes completo hasta 12; después 15 % más intereses de demora desde el día siguiente a esos 12 meses.
// Control de calidad 07-10-2026 (C2/M13): una sola regla, la del motor (recargoArt27). Devuelve también la etiqueta «15 % + intereses de demora…»
// para que ninguna pantalla rotule «(15 %)» un importe que incluye intereses.
// fiscal r4 (08-10-2026): con el territorio (ccaa), los forales usan su norma general tributaria (recargoPresentacion del motor).
function dgRecargo(cuota, limite, h, ccaa) {
  if (ccaa && typeof recargoPresentacion === "function") return recargoPresentacion(ccaa, cuota, limite, h, DG_I_DEMORA);
  if (typeof recargoArt27 === "function") return recargoArt27(cuota, limite, h, DG_I_DEMORA);
  if (!cuota || !limite || h <= limite) return { pct: 0, importe: 0, meses: 0, intereses: 0, etiqueta: "sin recargo" };
  const m = dgMesesEntre(limite, h);
  if (m < 12) return { pct: 0.01 + 0.01 * m, importe: dgR2(cuota * (0.01 + 0.01 * m)), meses: m, intereses: 0, etiqueta: `${m + 1} %` };
  const diasInt = Math.max(0, dgDias(dgMeses(limite, 12), h));
  const intereses = dgR2(cuota * DG_I_DEMORA * diasInt / 365);
  return { pct: 0.15, importe: dgR2(cuota * 0.15 + intereses), meses: m, intereses, etiqueta: "15 % + intereses de demora" };
}
function dgTramites(x, R) {
  if (!x.fecha) return [];
  if (typeof tramitesExp === "function") { try { return tramitesExp(x, R); } catch (e) {} }
  const st = x.tramites || {}, pers = x.personas || [], bienes = x.bienes || [];
  const ctx = { fecha: x.fecha, ccaa: x.ccaa, testamento: x.testamento, civil: x.civil, nHerederos: pers.filter((p) => !p.renuncia).length, hayConyuge: pers.some((p) => p.relacion === "conyuge" || p.relacion === "pareja_hecho"), hayMenores: pers.some((p) => dgEdadVale(p) && num(p.edad) < 18), hayRenuncia: pers.some((p) => p.renuncia), inmuebles: bienes.filter(dgInm).length, hayCuentas: bienes.some((b) => b.tipo === "cuenta"), hayValores: bienes.some((b) => b.tipo === "valores"), hayVehiculos: bienes.some((b) => b.tipo === "vehiculo"), hayEmpresa: bienes.some((b) => b.tipo === "empresa"), hayDeudas: (x.deudas || []).some((d) => num(d.importe) > 0), herederoUnico: pers.length === 1, hayLegados: bienes.some((b) => b.legatarioId), situ: { ...(x.situ || {}) } };
  return tramitesDe(ctx).map((t) => ({ ...t, st: st[t.id]?.estado || "pend" }));
}
const dgCerrado = (t) => t.st === "hecho" || t.st === "na";

// ── Motor del diagnóstico ──
function diagnostico(x, R) {
  const items = [], vistos = new Set(), h = dgHoy();
  const add = (o) => { const k = (o.titulo + "|" + (o.detalle || "")).toLowerCase().replace(/\s+/g, " "); if (vistos.has(k)) return null; vistos.add(k); const it = { tipo: "riesgo", gravedad: 1, estado: "VERIFICADO", ...o }; if (it.tipo === "oportunidad") it.gravedad = it.gravedad || 1; items.push(it); return it; };
  const pers = x.personas || [], bienes = x.bienes || [], vivos = pers.filter((p) => !p.renuncia);
  const st = x.tramites || {};
  const hecho = (id) => st[id]?.estado === "hecho" || st[id]?.estado === "na" || !!(x.tareas && x.tareas[id]);
  const alertasISD = R ? [...(R.isd.alertas || [])] : [];
  const consumir = (re) => { const out = []; for (let i = alertasISD.length - 1; i >= 0; i--) if (re.test(alertasISD[i])) out.unshift(alertasISD.splice(i, 1)[0]); return out; };
  let E = null; try { E = R ? estrategia(x) : null; } catch (e) { E = null; }
  const sim = (fn) => { try { const y = JSON.parse(JSON.stringify(x)); fn(y); const Ry = calcular(y); return Ry ? Ry.isd.total + Ry.totalPlus : null; } catch (e) { return null; } };
  const costeBase = R ? R.isd.total + R.totalPlus : 0;

  if (typeof vfItems === "function") { try { for (const it of vfItems(x, R)) add(it); } catch (e) {} }
  // ── Datos del expediente (funciona sin R) ──
  if (!x.fecha) add({ id: "sin-fecha", area: "datos", tipo: "dato", gravedad: 3, titulo: "Falta la fecha del fallecimiento", detalle: "Sin ella no hay plazos ni cálculo: todo el expediente cuelga de esa fecha.", accion: "Tómala del certificado de defunción.", enlace: { act: "editar" } });
  if (!x.ccaa) add({ id: "sin-terr", area: "datos", tipo: "dato", gravedad: 3, titulo: "Falta la comunidad autónoma", detalle: "La residencia fiscal del fallecido decide qué normativa de Sucesiones se aplica y cuánto se paga.", accion: "Indica dónde residió los últimos cinco años.", norma: "art. 32 Ley 22/2009", enlace: { act: "editar" } });
  if (!pers.length) add({ id: "sin-personas", area: "datos", tipo: "dato", gravedad: 3, titulo: "No hay herederos", detalle: "Sin herederos no hay reparto ni impuesto que calcular.", accion: "Añade al menos una persona.", enlace: { sec: "herencia" } });
  if (!bienes.length) add({ id: "sin-bienes", area: "datos", tipo: "dato", gravedad: 3, titulo: "No hay bienes", detalle: "El inventario está vacío: no se puede formar la masa hereditaria.", accion: "Añade los bienes del fallecido, aunque sea con valores aproximados.", enlace: { sec: "herencia" } });
  if (x.testamento === "nose") add({ id: "testamento-nose", area: "datos", tipo: "dato", gravedad: 2, titulo: "Aún no consta si hay testamento", detalle: "El cálculo se hace como si no lo hubiera. Con testamento cambian los herederos y las cuotas.", accion: "Pide el certificado de últimas voluntades (desde 15 días hábiles tras el fallecimiento).", enlace: { tramite: "ultimas" } });
  for (const p of pers) if (!p.nombre) add({ id: "sin-nombre-" + p.id, area: "datos", tipo: "dato", gravedad: 1, titulo: `Persona sin nombre (${RELACIONES[p.relacion]?.label.toLowerCase() || "heredero"})`, detalle: "Los documentos y las autoliquidaciones salen con el nombre en blanco.", accion: "Completa el nombre y apellidos.", enlace: { persona: p.id } });
  for (const b of bienes) {
    const n = dgNombreBien(b);
    if (!num(b.valor) && !num(b.valorReferencia)) add({ id: "valor-" + b.id, area: "datos", tipo: "dato", gravedad: 2, titulo: `${n}: sin valor`, detalle: "Un bien sin valor no computa en la masa ni en el impuesto.", accion: dgInm(b) ? "Indica el valor de mercado y el valor de referencia del Catastro." : "Indica el valor a la fecha del fallecimiento.", enlace: { bien: b.id } });
    if (!dgInm(b)) continue;
    const faltan = [!num(b.valorCatastralTotal) && "valor catastral total", !num(b.valorCatastralSuelo) && "valor catastral del suelo", !b.fechaAdq && "fecha de adquisición"].filter(Boolean);
    if (faltan.length) add({ id: "plus-datos-" + b.id, area: "datos", tipo: "dato", gravedad: 2, titulo: `${n}: falta ${faltan.join(", ")}`, detalle: "Sin estos datos no se puede calcular la plusvalía municipal ni valorar si conviene el método real.", accion: "Están en el último recibo del IBI y en la escritura de compra o herencia anterior.", norma: "arts. 104-107 TRLRHL", enlace: { bien: b.id } });
    else if (!num(b.valorAdq)) add({ id: "plus-adq-" + b.id, area: "datos", tipo: "dato", gravedad: 1, titulo: `${n}: sin valor de adquisición`, detalle: "Sin el precio al que lo adquirió el fallecido no se puede comprobar si el método real baja la plusvalía o si no hubo ganancia.", accion: "Toma el valor de la escritura por la que lo adquirió el fallecido.", norma: "art. 104.5 TRLRHL", enlace: { bien: b.id } });
    if (!num(b.valorReferencia)) add({ id: "vref-falta-" + b.id, area: "datos", tipo: "dato", gravedad: 2, titulo: `${n}: falta el valor de referencia`, detalle: "Es la base mínima en Sucesiones. Si se declara por debajo, Hacienda liquidará la diferencia.", accion: "Consúltalo en la Sede Electrónica del Catastro a la fecha del fallecimiento.", norma: "art. 9 Ley 29/1987", enlace: { bien: b.id } });
    if ((b.municipio || "OTRO") === "OTRO" && !b.muniNombre && (b.tipoManual == null || b.tipoManual === "")) add({ id: "muni-" + b.id, area: "datos", tipo: "dato", gravedad: 1, titulo: `${n}: municipio sin identificar`, detalle: "Sin municipio se aplica el tipo máximo legal del 30 % y ninguna bonificación.", accion: "Elige el municipio o introduce el tipo y la bonificación de su ordenanza.", norma: "art. 108 TRLRHL", enlace: { bien: b.id } });
  }
  const hayUsufructo = x.testamento === "usufructo" || (R && Object.values(R.isd.derechos || {}).some((L) => L.some((d) => d.tipo !== "pleno")));
  for (const a of consumir(/^Falta la edad de /)) { const nm = a.replace(/^Falta la edad de /, "").split(":")[0]; const p = pers.find((q) => q.nombre === nm); add({ id: "edad-" + (p ? p.id : nm), area: "datos", tipo: "dato", gravedad: hayUsufructo ? 2 : 1, titulo: `Falta la edad de ${nm}`, detalle: hayUsufructo ? "Se ha supuesto mayor de 21 años. La edad fija el valor del usufructo y el grupo de parentesco." : "Se ha supuesto mayor de 21 años. Si es menor de 21, cambia el grupo y la reducción.", accion: "Completa la edad a la fecha del fallecimiento.", norma: "arts. 20.2.a y 26 Ley 29/1987", enlace: p ? { persona: p.id } : { sec: "herencia" } }); }
  if (!R) for (const p of vivos) if (!dgEdadVale(p) && hayUsufructo) add({ id: "edad-" + p.id, area: "datos", tipo: "dato", gravedad: 2, titulo: `Falta la edad de ${dgNombre(p)}`, detalle: "Con usufructo, la edad fija cuánto vale cada derecho.", accion: "Completa la edad a la fecha del fallecimiento.", norma: "art. 26 Ley 29/1987", enlace: { persona: p.id } });
  for (const p of pers) { const d = p.discapacidad; if (d && (isNaN(Number(d)) || (num(d) > 0 && num(d) < 33))) add({ id: "disc-" + p.id, area: "datos", tipo: "dato", gravedad: 1, titulo: `${dgNombre(p)}: discapacidad sin grado válido`, detalle: "La reducción exige un grado reconocido del 33 % o más; con el dato actual no se aplica.", accion: "Anota el grado del certificado oficial (33-64 % o 65 % y más).", norma: "art. 20.2.a Ley 29/1987", enlace: { persona: p.id } }); }
  if (!x.responsable) add({ id: "sin-resp", area: "datos", tipo: "dato", gravedad: 1, titulo: "Sin abogado responsable", detalle: "Nadie figura como responsable: los avisos y la agenda no tienen destinatario.", accion: "Asigna el expediente a un miembro del despacho.", enlace: { sec: "despacho" } });
  if (!x.despacho?.ref) add({ id: "sin-ref", area: "datos", tipo: "dato", gravedad: 1, titulo: "Sin referencia del despacho", detalle: "Los escritos y el PDF salen sin número de expediente.", accion: "Asigna una referencia en Encargo y fondos.", enlace: { sec: "despacho" } });
  consumir(/datos de discapacidad/).forEach(() => add({ id: "disc-consent", area: "datos", tipo: "dato", gravedad: 1, titulo: "Datos de discapacidad: consentimiento explícito", detalle: "Son datos de categoría especial. Conviene dejar constancia del consentimiento del heredero para tratarlos.", accion: "Guarda el consentimiento firmado o el certificado aportado en el archivo del expediente.", norma: "art. 9 RGPD", enlace: { sec: "documentos" } }));

  if (!R) return dgCerrar(items, x, R);

  // ── Plazos ──
  const pl = Object.fromEntries((R.plazos || []).map((p) => [p.id, p]));
  const prorroga = st.prorroga?.estado === "hecho";
  if (pl.isd && !hecho("isd")) {
    const lim = prorroga ? dgMeses(x.fecha, 12) : pl.isd.limite, q = dgDias(h, lim);
    if (q < 0) {
      const rc = dgRecargo(R.isd.total, lim, h, x.ccaa);
      add({ id: "isd-vencido", area: "plazos", tipo: "riesgo", gravedad: 3, titulo: `Sucesiones fuera de plazo: ${dgPlural(-q, "día")} de retraso`, detalle: `El plazo${prorroga ? " prorrogado" : ""} venció el ${fechaCorta(lim)}. Presentar ahora sin requerimiento previo lleva un recargo del ${rc.etiqueta}${rc.importe ? `: ${eur(rc.importe)}` : ""}${rc.foral ? `. Territorio foral: ${rc.norma}${rc.estado === "PENDIENTE" ? " (en verificación)" : ""}.` : "; el recargo se reduce un 25 % si se paga todo al presentar (art. 27.5 LGT)."}`, accion: rc.foral ? "Presenta cuanto antes. Si ya hay requerimiento de Hacienda, cambia el régimen (sanción)." : "Presenta cuanto antes: el recargo sube un punto por cada mes completo. Si ya hay requerimiento de Hacienda, cambia el régimen (sanción).", euros: rc.importe, norma: rc.foral ? "norma general tributaria foral · plazo foral en verificación" : "art. 27 LGT · art. 67 RD 1629/1991", enlace: { tramite: "isd" } });
      if (pl.prescripcion) add({ id: "prescripcion", area: "plazos", tipo: "dato", gravedad: 1, titulo: `Hacienda puede liquidar hasta el ${fechaCorta(pl.prescripcion.limite)}`, detalle: "La prescripción corre cuatro años desde el fin del plazo voluntario y se interrumpe con cualquier actuación.", accion: "No cuentes con la prescripción: regulariza y guarda los justificantes.", norma: "arts. 66-67 LGT", enlace: { tramite: "prescripcion" } });
    } else if (q <= 30) add({ id: "isd-30", area: "plazos", tipo: "riesgo", gravedad: 2, titulo: `Sucesiones: vence en ${dgPlural(q, "día")}`, detalle: `Último día ${fechaCorta(lim)}${prorroga ? " (con la prórroga concedida)" : ""}. Pasado el plazo hay recargo${x.ccaa === "GIP" ? " del 2 % los tres primeros meses, más intereses (Gipuzkoa)" : ["NAV", "ALA", "BIZ"].includes(x.ccaa) ? " según la norma general tributaria foral" : " del 1 % más 1 % por mes"}.`, accion: prorroga || h > (pl.prorroga_isd?.limite || "") ? "Cierra la autoliquidación y el pago antes de esa fecha; si falta liquidez, valora aplazar o fraccionar." : "Presenta o pide la prórroga antes de que se agote la ventana.", norma: "art. 67 RD 1629/1991 · art. 27 LGT", enlace: { tramite: "isd" } });
    else if (q <= 60) add({ id: "isd-60", area: "plazos", tipo: "dato", gravedad: 1, titulo: `Sucesiones: quedan ${dgPlural(q, "día")}`, detalle: `Último día ${fechaCorta(lim)}${prorroga ? " (con prórroga)" : ""}.`, accion: "Planifica la firma y el pago con margen.", norma: "art. 67 RD 1629/1991", enlace: { tramite: "isd" } });
    if (!prorroga && q >= 0 && pl.prorroga_isd) {
      const qp = dgDias(h, pl.prorroga_isd.limite);
      const palPlazo = E && E.P.find((p) => p.id === "plazo");
      if (qp >= 0 && qp <= 45 && !hecho("particion")) add({ id: "prorroga-ventana", area: "plazos", tipo: "oportunidad", titulo: `Aún se puede pedir la prórroga: ${dgPlural(qp, "día")}`, detalle: `Hasta el ${fechaCorta(pl.prorroga_isd.limite)}. Da seis meses más a cambio solo de intereses de demora, sin recargo.`, accion: "Si la escritura no va a estar a tiempo, presenta la solicitud de prórroga ahora.", euros: palPlazo && palPlazo.estado === "si" ? palPlazo.ahorro : undefined, norma: "art. 68 RD 1629/1991", enlace: { doc: "prorroga" } });
      else if (qp < 0) add({ id: "prorroga-fuera", area: "plazos", tipo: "dato", gravedad: 1, titulo: "Ya no cabe pedir la prórroga", detalle: `La ventana de cinco meses terminó el ${fechaCorta(pl.prorroga_isd.limite)}. Hay que presentar antes del ${fechaCorta(lim)}.`, accion: "Si no habrá escritura a tiempo, presenta la autoliquidación con los datos disponibles y rectifica después.", norma: "art. 68 RD 1629/1991 · art. 120.3 LGT", enlace: { tramite: "isd" } });
    }
  }
  if (pl.plusvalia && !hecho("plusvalia") && bienes.some(dgInm)) {
    const lim = pl.plusvalia.limite, q = dgDias(h, lim);
    if (q < 0) { const rc = dgRecargo(R.totalPlus, lim, h); add({ id: "plus-vencido", area: "plazos", tipo: "riesgo", gravedad: 3, titulo: `Plusvalía fuera de plazo: ${dgPlural(-q, "día")} de retraso`, detalle: `El plazo de seis meses venció el ${fechaCorta(lim)}. Recargo del ${rc.etiqueta} y, además, las bonificaciones son rogadas: varias ordenanzas exigen pedirlas en plazo.`, accion: "Declara ahora en cada ayuntamiento y solicita la bonificación; si no se pidió prórroga, comprueba en la ordenanza si aún cabe.", euros: rc.importe || undefined, norma: "art. 110 TRLRHL · art. 27 LGT", enlace: { tramite: "plusvalia" } }); }
    else if (q <= 30) add({ id: "plus-30", area: "plazos", tipo: "riesgo", gravedad: 2, titulo: `Plusvalía: vence en ${dgPlural(q, "día")}`, detalle: `Último día ${fechaCorta(lim)}, prorrogable hasta un año si se pide antes de que venza.`, accion: "Presenta la declaración con la solicitud de bonificación en cada ayuntamiento.", norma: "art. 110 TRLRHL", enlace: { tramite: "plusvalia" } });
    else if (q <= 60) add({ id: "plus-60", area: "plazos", tipo: "dato", gravedad: 1, titulo: `Plusvalía: quedan ${dgPlural(q, "día")}`, detalle: `Último día ${fechaCorta(lim)}.`, accion: "Reúne los datos catastrales y decide quién se adjudica cada inmueble.", norma: "art. 110 TRLRHL", enlace: { tramite: "plusvalia" } });
  }
  if (pl.irpf && !hecho("irpf")) {
    if (h > pl.irpf.limite) add({ id: "irpf-vencido", area: "plazos", tipo: "riesgo", gravedad: 2, titulo: "Renta del fallecido sin presentar", detalle: `La campaña del ejercicio ${x.fecha.slice(0, 4)} terminó el ${fechaCorta(pl.irpf.limite)}. Los herederos responden de la deuda del causante.`, accion: "Presenta la declaración fuera de plazo; si sale a devolver, usa el modelo H-100.", norma: "art. 96 Ley 35/2006 · art. 39 LGT", enlace: { tramite: "irpf" } });
    else if (h >= pl.irpf.desde) add({ id: "irpf-abierta", area: "plazos", tipo: "riesgo", gravedad: 1, titulo: `Renta del fallecido: campaña abierta hasta el ${fechaCorta(pl.irpf.limite)}`, detalle: "La última declaración del causante la presentan los herederos; suele salir a devolver.", accion: "Reúne los datos fiscales del fallecido y presenta la declaración en plazo.", norma: "art. 96 Ley 35/2006", enlace: { tramite: "irpf" } });
  }
  // C2: «dentro de plazo» se deriva de las fechas salvo que el abogado lo haya fijado (dgPlazoInfo). Se dan las dos cifras.
  const PZ = dgPlazoInfo(x);
  if (!PZ.enPlazo) { const c = sim((y) => { y.enPlazo = true; y.enPlazoManual = true; }); const perd = c != null ? dgR2(costeBase - c) : 0; const rec = R.isd.recargo; add({ id: "enplazo", area: "plazos", tipo: "riesgo", gravedad: perd > 0 || PZ.auto ? 3 : 2, titulo: PZ.auto ? `Plazo de Sucesiones vencido: se calcula fuera de plazo` : "El expediente se calcula como presentado fuera de plazo", detalle: `${PZ.auto ? `El plazo venció el ${fechaCorta(PZ.plazo.limite)}${PZ.plazo.prorroga ? " (con la prórroga)" : " y no consta prórroga concedida"}, así que el cálculo ya es el de una presentación tardía. ` : ""}${perd > 0 ? `Se pierden bonificaciones que exigen presentar en plazo: ${eur0(perd)} más de Sucesiones (${eur0(c)} si se hubiera presentado a tiempo, ${eur0(R.isd.total)} ahora). ` : ""}${rec && rec.importe ? `Recargo estimado a hoy: ${eur(rec.importe)} (${rec.etiqueta}).` : "Hay recargo del art. 27 LGT sobre la cuota."}`, accion: PZ.auto ? "Si se concedió la prórroga, márcala en Trámites; si se presentó a tiempo, corrige el interruptor en Impuestos. Si no, presenta cuanto antes." : "Si aún estás en plazo, corrige la marca en Impuestos; si no, valora presentar ya para frenar el recargo.", euros: dgR2((perd > 0 ? perd : 0) + (rec ? rec.importe : 0)) || undefined, norma: "art. 27 LGT · arts. 67-68 RD 1629/1991", enlace: { sec: "impuestos" } }); consumir(/^Recargo estimado por presentar|^Presentación fuera de plazo/); }
  for (const a of consumir(/^Fuera de plazo: no se ha cotejado si las bonificaciones/)) add({ id: "bonif-plazo-pend", area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: "¿La bonificación exige presentar en plazo?", detalle: a, accion: "Coteja la norma autonómica antes de presentar.", estado: "PENDIENTE", enlace: { sec: "impuestos" } });

  // ── Impuestos ──
  const permAl = consumir(/la reducción por vivienda habitual exige mantenerla (\d+) años/);
  if (permAl.length) {
    const anios = permAl[0].match(/mantenerla (\d+) años/)[1], nombres = permAl.map((a) => a.split(":")[0]);
    const c = sim((y) => { y.noAplicarVivienda = true; }); const vale = c != null ? dgR2(c - costeBase) : 0;
    add({ id: "viv-permanencia", area: "impuestos", tipo: "riesgo", gravedad: 1, titulo: `Reducción por vivienda habitual: mantenerla ${anios} años`, detalle: `${nombres.join(", ")} ${nombres.length > 1 ? "aplican" : "aplica"} la reducción${vale ? `, que vale ${eur0(vale)}` : ""}. Si la vivienda se vende antes, se devuelve con intereses.`, accion: "Advierte por escrito a los herederos y, si hay venta prevista, márcalo en Estrategia fiscal para calcular sin la reducción.", euros: vale || undefined, norma: (R.isd.herederos.flatMap((q) => q.traza).find((t) => /vivienda habitual/i.test(t.paso) && t.norma) || {}).norma || "art. 20.2.c Ley 29/1987", estado: (R.isd.herederos.flatMap((q) => q.traza).find((t) => /vivienda habitual/i.test(t.paso) && t.estado) || {}).estado || "VERIFICADO", enlace: { sec: "estrategia" } });
    if (x.ventaVivienda) add({ id: "viv-venta", area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: "Venta de la vivienda prevista antes del plazo", detalle: "Con venta prevista, la reducción se perdería y habría que devolverla con intereses.", accion: "Calcula el escenario sin reducción y decide con el cliente antes de presentar.", norma: "art. 20.2.c Ley 29/1987", enlace: { sec: "estrategia" } });
  }
  const vivNo = consumir(/no se aplica la reducción por vivienda habitual/);
  if (vivNo.length) { const nombres = vivNo.map((a) => a.split(":")[0]); const porDecision = /venta prevista/.test(vivNo[0]); add({ id: "viv-no", area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${nombres.join(", ")}: la reducción por vivienda no llega a aplicarse`, detalle: porDecision ? "Se ha desactivado por decisión del expediente (venta prevista antes del plazo de mantenimiento)." : "La base ya queda en 0 € con las demás reducciones, así que no nace la obligación de mantener la vivienda.", accion: porDecision ? "Si la venta se descarta, reactiva la reducción en Estrategia fiscal." : "Nada que hacer; conviene que el cliente sepa que no hay obligación de mantener la vivienda.", norma: "art. 20.2.c Ley 29/1987", enlace: { sec: porDecision ? "estrategia" : "impuestos" } }); }
  for (const a of consumir(/STSJ Andalucía 1011\/2026/)) add({ id: "viv-tsja", area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: "Reducción de vivienda íntegra al adjudicatario: criterio litigioso", detalle: "La Agencia Tributaria de Andalucía la reparte por cuotas; el TSJ de Andalucía la aplicó íntegra. Presentar así puede acabar en liquidación y recurso.", accion: "Vía prudente: autoliquidar por cuotas y pedir la rectificación con devolución. Informe expreso al cliente.", norma: "STSJ Andalucía 1011/2026 · art. 120.3 LGT", estado: "PENDIENTE", enlace: { sec: "estrategia" } });
  const parejaNo = pers.filter((p) => !p.renuncia && ((p.relacion === "pareja_hecho" && !p.inscrita) || p.relacion === "pareja_no_inscrita"));
  consumir(/Pareja de hecho no inscrita/);
  for (const p of parejaNo) { const c = sim((y) => { const q = y.personas.find((z) => z.id === p.id); q.relacion = "pareja_hecho"; q.inscrita = true; }); const dif = c != null ? dgR2(costeBase - c) : 0; add({ id: "pareja-" + p.id, area: "impuestos", tipo: "riesgo", gravedad: 3, titulo: `${dgNombre(p)}: pareja de hecho sin inscripción acreditada`, detalle: `Sin inscripción en un registro oficial tributa como extraño (grupo IV)${dif > 0 ? `: ${eur0(dif)} más que equiparada al cónyuge` : ""}. Sin testamento, además, la pareja no hereda por ley.`, accion: "Pide el certificado del registro de parejas de hecho; si consta inscrita, márcalo en su ficha.", euros: dif || undefined, norma: R.isd.norma || "normativa autonómica del ISD", estado: "PENDIENTE", enlace: { persona: p.id } }); }
  if ((x.ajuar || "sts") === "3pct") { const pa = E && E.P.find((p) => p.id === "ajuar"); add({ id: "ajuar", area: "impuestos", tipo: "oportunidad", titulo: "Ajuar doméstico: aplicar el criterio del Supremo", detalle: "El 3 % se calcula solo sobre las viviendas de uso residencial no alquiladas, no sobre dinero ni valores; bienes de uso personal y doméstico.", accion: "Cambia el criterio del ajuar en Impuestos y deja constancia de la jurisprudencia en la autoliquidación.", euros: pa && pa.ahorro > 0 ? pa.ahorro : undefined, norma: "SSTS 342/2020 y 499/2020 · art. 15 Ley 29/1987", enlace: { sec: "impuestos" } }); }
  for (const p of pers.filter((q) => num(q.seguro) > 0)) { const hh = R.isd.herederos.find((q) => q.id === p.id); const red = hh && hh.traza.find((t) => /seguros de vida/i.test(t.paso) && t.valor < 0); if (hh && !red) add({ id: "seguro-" + p.id, area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${dgNombre(p)}: seguro de vida sin reducción`, detalle: `Cobra ${eur0(num(p.seguro))}. La reducción por seguros solo alcanza a cónyuge, ascendientes y descendientes.`, accion: "Comprueba el parentesco y quién pagaba las primas: si era el propio beneficiario, tributa en IRPF, no en Sucesiones.", norma: "art. 20.2.b Ley 29/1987", enlace: { persona: p.id } }); }
  // Plusvalía por inmueble
  for (const { b, r } of R.plus) {
    const n = dgNombreBien(b);
    const bon = r.porTitular.filter((t) => t.bonificacion > 0);
    if (bon.length) add({ id: "plus-rogada-" + b.id, area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: `${n}: la bonificación de plusvalía hay que pedirla`, detalle: `Se ha calculado una bonificación de ${eur0(bon.reduce((s, t) => s + t.bonificacion, 0))} en ${r.municipio}. Es rogada: si no se solicita expresamente, se paga la cuota entera.`, accion: "Incluye la solicitud de bonificación en la declaración de cada adjudicatario y acredita los requisitos (padrón, parentesco).", euros: bon.reduce((s, t) => s + t.bonificacion, 0), norma: bon[0].norma || "art. 108.4 TRLRHL", estado: bon[0].estado === "VERIFICADO" ? "VERIFICADO" : "PENDIENTE", enlace: { tramite: "plusvalia" } });
    if (r.noSujeto) add({ id: "plus-nosujeto-" + b.id, area: "impuestos", tipo: "oportunidad", titulo: `${n}: sin plusvalía por falta de ganancia`, detalle: `El valor de adquisición (${eur0(num(b.valorAdq))}) iguala o supera el de transmisión: la herencia de este inmueble no está sujeta.`, accion: "Declara igualmente en plazo y aporta las escrituras que acrediten los dos valores.", euros: dgR2(r.baseObjetiva * r.tipo), norma: "art. 104.5 TRLRHL · STC 59/2017", enlace: { tramite: "plusvalia_real" } });
    else if (r.metodo === "real") add({ id: "plus-real-" + b.id, area: "impuestos", tipo: "oportunidad", titulo: `${n}: tributa por la ganancia real, no por el coeficiente`, detalle: `La base real (${eur0(r.baseReal)}) es menor que la objetiva (${eur0(r.baseObjetiva)}). Hay que pedirlo y acreditarlo.`, accion: "Aporta la escritura de adquisición y el valor de referencia o de transmisión al declarar.", euros: dgR2((r.baseObjetiva - r.baseReal) * r.tipo), norma: "art. 107.5 TRLRHL", enlace: { tramite: "plusvalia_real" } });
    if (r.estimacion && r.estimacion.hacienda && !r.estimacion.bonifManual) add({ id: "plus-hac-" + b.id, area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${n}: plusvalía con el tipo oficial y sin bonificación`, detalle: `${b.muniNombre || r.municipio}: tipo del ${grp(r.tipo * 100, 2)} % comunicado por el Ayuntamiento a Hacienda para 2026 y coeficientes máximos (${eur0(r.total)}). Hacienda no publica las bonificaciones: si la ordenanza prevé una para herencias, la cuota real será menor.`, accion: `Comprueba en la ordenanza fiscal de ${b.muniNombre || r.municipio}${r.estimacion.bop ? " (" + r.estimacion.bop.nombre + ")" : ""} la bonificación por causa de muerte y sus requisitos, e introdúcela en la ficha del bien.`, norma: "arts. 107.4, 108.1 y 108.4 TRLRHL", estado: "VERIFICADO", enlace: { bien: b.id } });
    else if (r.estimacion && !r.estimacion.manual && !r.estimacion.hacienda && b.muniNombre) add({ id: "plus-est-" + b.id, area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${n}: plusvalía estimada con el tipo máximo legal`, detalle: `La ordenanza de ${b.muniNombre} no está incorporada: se calcula con el 30 %, los coeficientes máximos y sin bonificación (${eur0(r.total)}). La cuota real será igual o menor.`, accion: `Consulta la ordenanza fiscal de ${b.muniNombre}${r.estimacion.bop ? " (" + r.estimacion.bop.nombre + ")" : ""} e introduce su tipo y su bonificación en la ficha del bien.`, norma: "arts. 107.4 y 108.1 TRLRHL", estado: "VERIFICADO", enlace: { bien: b.id } });
    if ((b.municipio || "OTRO") === "OTRO" && b.tipoManual != null && b.tipoManual !== "") add({ id: "plus-manual-" + b.id, area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${n}: tipo de plusvalía introducido a mano (${grp(num(b.tipoManual), 2)} %)`, detalle: `${r.municipio} no está en el catálogo de ordenanzas: el tipo${num(b.bonifManual) ? ` y la bonificación del ${grp(num(b.bonifManual), 0)} %` : ""} son los que se han tecleado.`, accion: "Cotéjalos con la ordenanza fiscal vigente del ayuntamiento a la fecha del fallecimiento.", norma: "art. 108 TRLRHL", estado: "PENDIENTE", enlace: { bien: b.id } });
    else if (r.estadoTipo === "PENDIENTE" && !(r.alertas || []).some((a) => /foral/i.test(a))) { const L = R.plus.filter((q) => q.r.municipio === r.municipio && q.r.estadoTipo === "PENDIENTE"); add({ id: "plus-rev-" + r.municipio, area: "impuestos", tipo: "dato", gravedad: 1, titulo: `Ordenanza de ${r.municipio} en verificación`, detalle: `${L.map((q) => dgNombreBien(q.b)).join(", ")}: el tipo del ${grp(r.tipo * 100, 2)} % o la bonificación no se han cotejado con el texto oficial vigente.`, accion: "Comprueba la ordenanza en la web del ayuntamiento antes de presentar.", norma: `Ordenanza fiscal IIVTNU de ${r.municipio}`, estado: "PENDIENTE", enlace: { sec: "impuestos" } }); }
    for (const a of r.alertas || []) { if (/foral/i.test(a)) add({ id: "plus-foral-" + b.id, area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: `${n}: plusvalía en territorio foral`, detalle: "La norma foral tiene coeficientes, tipos y bonificaciones propios. El cálculo mostrado usa las reglas estatales y es solo orientativo.", accion: "Liquida con la norma foral del territorio o consulta al ayuntamiento antes de dar cifras al cliente.", norma: "Norma foral del IIVTNU", estado: "PENDIENTE", enlace: { bien: b.id } }); else add({ id: "plus-al-" + b.id + "-" + a.slice(0, 12), area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${n}: aviso de la ordenanza`, detalle: a, accion: "Revisa la liquidación de este inmueble.", norma: `Ordenanza fiscal IIVTNU de ${r.municipio}`, estado: "PENDIENTE", enlace: { sec: "impuestos" } }); }
  }
  // M11 · fecha de adquisición imposible · D3 · bonificación de la ordenanza sin introducir (control de calidad 07-10-2026)
  for (const b of bienes.filter((q) => dgInm(q) && q.fechaAdq && x.fecha && q.fechaAdq > x.fecha)) add({ id: "adq-futura-" + b.id, area: "datos", tipo: "dato", gravedad: 3, titulo: `${dgNombreBien(b)}: fecha de adquisición posterior al fallecimiento`, detalle: `Consta adquirido el ${fechaCorta(b.fechaAdq)} y el fallecimiento es del ${fechaCorta(x.fecha)}: es imposible. La plusvalía se calcula con el coeficiente máximo y sin método real (cuota máxima posible) hasta que se corrija.`, accion: "Toma la fecha de la escritura por la que lo adquirió el fallecido.", norma: "arts. 104.5 y 107.4 TRLRHL", enlace: { bien: b.id } });
  for (const { b, r } of R.plus) { const pend = r.porTitular.filter((t) => t.bonifPendiente); if (pend.length) add({ id: "plus-bonif-pend-" + b.id, area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: `${dgNombreBien(b)}: bonificación de ${r.municipio} sin introducir`, detalle: `La ordenanza de ${r.municipio} prevé una bonificación por herencia que el programa no ha podido cotejar, y no se ha indicado el porcentaje: la plusvalía (${eur0(r.total)}) es la máxima posible. ${pend[0].norma}.`, accion: "Consulta la ordenanza vigente e indica el porcentaje de bonificación en la ficha del inmueble.", norma: "art. 108.4 TRLRHL", estado: "PENDIENTE", enlace: { bien: b.id } }); }
  // Valor declarado frente a valor de referencia
  for (const b of bienes.filter((q) => dgInm(q) && num(q.valor) && num(q.valorReferencia))) {
    const n = dgNombreBien(b), v = num(b.valor), vr = num(b.valorReferencia);
    if (vr > v * 1.03) { const pal = E && E.P.find((p) => p.id === "vref-" + b.id); add({ id: "vref-" + b.id, area: "impuestos", tipo: pal && pal.estado === "si" ? "oportunidad" : "dato", gravedad: 1, titulo: `${n}: el valor de referencia supera al de mercado`, detalle: `Referencia ${eur0(vr)} frente a ${eur0(v)} declarados. Se liquida por el mayor; declarar por debajo abre una comprobación segura.${pal && pal.estado === "si" ? " Cabe impugnarlo con tasación y pedir la rectificación." : ""}`, accion: pal && pal.estado === "si" ? "Valora encargar una tasación y pedir la rectificación tras autoliquidar por referencia." : "Autoliquida por el valor de referencia; si el cliente discrepa, hace falta tasación.", euros: pal && pal.estado === "si" ? pal.ahorro : undefined, norma: "art. 9 Ley 29/1987 · art. 120.3 LGT", enlace: { sec: "estrategia" } }); }
    else if (v > vr * 1.03) { const pal = E && E.P.find((p) => p.id === "valor-" + b.id); add({ id: "valor-alto-" + b.id, area: "impuestos", tipo: "oportunidad", titulo: `${n}: se declara por encima del valor de referencia`, detalle: `${eur0(v)} frente a ${eur0(vr)} de referencia. ${pal && pal.estado === "si" ? `Declarar por referencia ahorra ${eur0(pal.ahorro)} netos aun contando el IRPF de una venta futura.` : "Cuesta algo más de Sucesiones hoy, pero ese valor será el de adquisición en el IRPF si se vende: protege frente a una ganancia mayor."}`, accion: pal && pal.estado === "si" ? "Valora declarar por el valor de referencia." : "Decisión consciente con el cliente: mantener el valor alto si prevé vender.", euros: pal && pal.estado === "si" ? pal.ahorro : undefined, norma: "art. 9 Ley 29/1987 · art. 36 Ley 35/2006", enlace: { sec: "estrategia" } }); }
  }
  // Palancas de Estrategia fiscal aún no recogidas
  if (E) for (const p of E.P.filter((q) => q.estado === "si" && q.ahorro > 0)) { if (["ajuar", "plazo"].includes(p.id) || /^(valor|vref)-/.test(p.id)) continue; add({ id: "pal-" + p.id, area: p.id === "lotes" || p.id === "renuncia" ? "reparto" : "impuestos", tipo: "oportunidad", titulo: p.titulo, detalle: `${(p.sub || "").replace(/\s+a\s*$/, "")}${p.sub ? ". " : ""}${p.riesgo === "alto" || p.riesgo === "litigioso" ? "Riesgo " + p.riesgo + ": solo con informe expreso al cliente." : "Riesgo " + (p.riesgo || "bajo") + "."}`, accion: p.aplicar ? "Pruébalo como escenario en Estrategia fiscal y decide con el cliente." : "Revísalo en Estrategia fiscal.", euros: p.ahorro, norma: p.norma, estado: /verificación|PENDIENTE/i.test(p.norma || "") ? "PENDIENTE" : "VERIFICADO", enlace: { sec: "estrategia" } }); }
  for (const a of consumir(/incompatible con la bonificación/)) add({ id: "cat-empresa", area: "impuestos", tipo: "riesgo", gravedad: 2, titulo: "Cataluña: reducción de empresa o bonificación, no las dos", detalle: a, accion: "Compara ambas vías antes de presentar.", norma: "Libro VI CTC", enlace: { sec: "impuestos" } });
  if (R.isd.pendientes && R.isd.pendientes.length) add({ id: "isd-pendientes", area: "impuestos", tipo: "dato", gravedad: 1, titulo: `${dgPlural(R.isd.pendientes.length, "parámetro")} del cálculo en verificación`, detalle: R.isd.pendientes.slice(0, 3).join("; ") + (R.isd.pendientes.length > 3 ? "…" : "") + ".", accion: "Cotéjalos con la norma autonómica vigente antes de dar la cifra por definitiva.", norma: R.isd.norma, estado: "PENDIENTE", enlace: { sec: "normativa" } });

  // ── Reparto y legítimas ──
  if (x.testamento === "porcentajes") { const tot = pers.reduce((s, p) => s + num(p.pct), 0); if (pers.length && Math.abs(tot - 100) > 0.01) add({ id: "pct-100", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: `Los porcentajes suman ${grp(tot, tot % 1 ? 2 : 0)} %, no 100 %`, detalle: "El cálculo los ha normalizado, pero un testamento que no cierra el 100 % deja parte de la herencia sin destino o mal repartida.", accion: "Revisa las cuotas del testamento; lo que no se disponga se rige por la sucesión intestada.", norma: "art. 912 CC", enlace: { sec: "herencia" } }); }
  for (const a of consumir(/Posible lesión de la legítima de ([^:]+):/)) { const nm = a.match(/legítima de ([^:]+):/)[1]; const m = a.match(/recibe ([\d.]+) € y su legítima estricta aproximada es ([\d.]+) €/); add({ id: "legitima-" + nm, area: "reparto", tipo: "riesgo", gravedad: 3, titulo: `${nm} recibe menos que su legítima estricta`, detalle: m ? `Recibe ${m[1]} € y su legítima estricta ronda los ${m[2]} €. Puede pedir el complemento y, si hace falta, reducir legados o cuotas de los demás.` : a, accion: "Comprueba el cómputo de la legítima y prevé el complemento o la conformidad expresa del legitimario en la escritura.", euros: m ? dgR2(num(m[2]) - num(m[1])) : undefined, norma: "arts. 806-808, 815 y 818 CC", enlace: { sec: "particion" } }); }
  for (const a of consumir(/Los legados superan el tercio/)) add({ id: "legados-tercio", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: "Los legados superan el tercio de libre disposición", detalle: "Pueden ser inoficiosos y reducirse para pagar las legítimas.", accion: "Calcula las legítimas antes de entregar los legados.", norma: "arts. 817-820 CC", enlace: { sec: "particion" } });
  consumir(/Hay renuncias: deben hacerse ante notario/).forEach(() => add({ id: "renuncia-forma", area: "reparto", tipo: "riesgo", gravedad: 1, titulo: `Renuncia de ${pers.filter((p) => p.renuncia).map(dgNombre).join(", ")}: ante notario y sin haber aceptado`, detalle: "La renuncia solo vale en escritura pública y antes de cualquier acto que suponga aceptación (cobrar saldos, vender, pagar deudas propias).", accion: "Firma la renuncia cuanto antes y que el renunciante no gestione nada de la herencia mientras tanto.", norma: "arts. 999 y 1008 CC", enlace: { doc: "renuncia" } }));
  consumir(/tributa por ella con el parentesco del renunciante/).forEach(() => add({ id: "renuncia-28", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: "Renuncia: el beneficiario tributa con el parentesco del renunciante", detalle: "Si quien recibe la parte renunciada tiene un parentesco más lejano que el renunciante, se le aplica el del renunciante cuando es más gravoso.", accion: "Revisa la cuota de los beneficiarios antes de decidir la renuncia; hecha a favor de alguien concreto, es donación.", norma: "art. 28 Ley 29/1987 · art. 1000 CC", enlace: { sec: "impuestos" } }));
  consumir(/herederos menores de edad/).forEach(() => add({ id: "menores", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: `Herederos menores: ${vivos.filter((p) => dgEdadVale(p) && num(p.edad) < 18).map(dgNombre).join(", ") || "hay menores"}`, detalle: "Si sus padres también heredan hay conflicto de intereses: hace falta defensor judicial, y la partición necesita aprobación judicial.", accion: "Pide el nombramiento de defensor judicial antes de la escritura y prevé la aprobación judicial de la partición.", norma: "arts. 163 y 1060 CC", enlace: { tramite: "menores" } }));
  const discAdj = vivos.filter((p) => num(p.discapacidad) >= 33);
  if (discAdj.length) add({ id: "disc-apoyos", area: "reparto", tipo: "dato", gravedad: 1, titulo: `${discAdj.map(dgNombre).join(", ")}: comprobar medidas de apoyo para partir`, detalle: "Si interviene un curador con facultades de representación, la partición necesita aprobación judicial.", accion: "Pregunta si hay curatela o poderes preventivos y adjunta la resolución al expediente.", norma: "art. 1060 CC · Ley 8/2021", enlace: { tramite: "apoyos" } });
  let PT = null; try { PT = particion(x, R); } catch (e) { PT = null; }
  { const C = PT && typeof cuadroParticion === "function" ? cuadroParticion(x, R) : null;
    if (C && C.excesos.length) {
      const terr = C.terr, d = x.firma && x.firma.dec && x.firma.dec.compensacion, sig = JSON.stringify(C.compensaciones.map((c) => [c.de.id, c.a.id, Math.round(c.importe)])), declarada = !!(d && d.sig === sig);
      add({ id: "excesos", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: `Exceso de adjudicación: ${C.excesos.map((e) => `${dgNombre(e.p)} ${eur0(e.exceso)}`).join(", ")}`, detalle: `${cpTxtCompensaciones(C)}. ${C.excesos.map((e) => `${e.txtCoste}.${e.sugerencia ? " " + e.sugerencia : ""}`).join(" ")} ${declarada ? "La compensación en dinero ya está declarada en Listo para firmar." : "Falta declarar la compensación en dinero en Listo para firmar: sin ella, el exceso sería una donación."}`, accion: "Recoge la compensación y la indivisibilidad del bien en el cuaderno particional.", euros: C.coste || undefined, norma: C.T.ajdNorma + " · art. 1062 CC", estado: C.pendiente ? "PENDIENTE" : "VERIFICADO", enlace: { sec: "particion" } });
      for (const a of C.avisos) add({ id: "liquidez-" + a.id, area: "reparto", tipo: "riesgo", gravedad: 2, titulo: a.titulo, detalle: `${a.detalle} Alternativas: ${a.alternativas.map((q) => q.t.replace(/\.$/, "")).join("; ")}.`, accion: "Valora con la familia cómo se paga la compensación antes de fijar la adjudicación.", norma: "art. 1062 CC", estado: "VERIFICADO", enlace: { sec: "particion" } });
    } }
  if (hayUsufructo && vivos.length > 1 && !(E && E.P.some((p) => p.id === "pal-conmutacion"))) add({ id: "conmutacion", area: "reparto", tipo: "oportunidad", titulo: "Conmutar el usufructo del viudo", detalle: "Los herederos pueden pagar el usufructo con bienes concretos, un capital o una renta: evita el proindiviso y permite vender sin esperar.", accion: "Plantéalo a la familia antes de la escritura; conmutado según la ley no es exceso de adjudicación.", norma: "arts. 839-840 CC", enlace: { tramite: "conmutacion" } });
  // I6 · Vecindad civil y reparto foral; I7 · más deudas que bienes; I8 · legado a persona quitada
  for (const a of consumir(/^Reparto legal no calculado/)) add({ id: "foral-bloqueo", area: "reparto", tipo: "riesgo", gravedad: 3, titulo: R.isd.bloqueo ? R.isd.bloqueo.titulo : "Reparto legal no calculado", detalle: R.isd.bloqueo ? R.isd.bloqueo.motivo : a, accion: "Introduce el reparto que resulte del derecho foral (testamento › porcentajes) o corrige la vecindad civil en Herederos y bienes.", norma: R.isd.bloqueo ? R.isd.bloqueo.norma : "arts. 9.8 y 14-16 CC", estado: "PENDIENTE", enlace: { sec: "herencia" } });
  for (const a of consumir(/^Vecindad civil .* supuesta por la residencia/)) add({ id: "vecindad-supuesta", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: "Vecindad civil del causante sin confirmar", detalle: a, accion: "Confírmala (certificado de nacimiento, declaraciones de vecindad, padrón histórico) e indícala en Herederos y bienes.", norma: "arts. 9.8 y 14-16 CC", estado: "VERIFICADO", enlace: { sec: "herencia" } });
  for (const a of consumir(/^Vecindad civil .*indicada en el expediente/)) add({ id: "vecindad", area: "reparto", tipo: "dato", gravedad: 1, titulo: "Vecindad civil indicada en el expediente", detalle: a, accion: "Conserva la prueba de la vecindad en el archivo del expediente.", norma: "arts. 9.8 y 14-16 CC", estado: "VERIFICADO", enlace: { sec: "herencia" } });
  for (const a of consumir(/^Más deudas que bienes/)) add({ id: "pasivo", area: "reparto", tipo: "riesgo", gravedad: 3, titulo: `Más deudas que bienes: el pasivo supera al activo en ${eur0(R.isd.masa.pasivoExcede || 0)}`, detalle: a, accion: "Antes de que nadie acepte (ni de forma tácita), plantea a cada heredero aceptar a beneficio de inventario o renunciar ante notario.", euros: R.isd.masa.pasivoExcede || undefined, norma: "arts. 999, 1003, 1008, 1010-1016 y 1023 CC", estado: "VERIFICADO", enlace: { tramite: "inventario_plazo" } });
  for (const a of consumir(/^Los legados \(.*\) superan lo que queda/)) add({ id: "legados-pasivo", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: "Los legados superan la herencia líquida", detalle: a, accion: "Paga primero a los acreedores y reduce los legados; valora el beneficio de inventario.", norma: "arts. 887-891, 1003 y 1027 CC", enlace: { sec: "herencia" } });
  for (const a of consumir(/figura como legado a una persona que ya no está/)) { const b = bienes.find((q) => a.startsWith(q.descripcion || "Un bien")); add({ id: "legado-huerfano-" + (b ? b.id : a.slice(0, 12)), area: "datos", tipo: "dato", gravedad: 2, titulo: `${b ? dgNombreBien(b) : "Un bien"}: legado a una persona que ya no está`, detalle: a, accion: "Abre el bien y elige el legatario correcto o quita la marca de legado.", enlace: b ? { bien: b.id } : { sec: "herencia" } }); }
  for (const a of consumir(/derecho civil propio/)) add({ id: "foral-civil", area: "reparto", tipo: "riesgo", gravedad: 2, titulo: "Territorio con derecho civil propio", detalle: a, accion: "Confirma la vecindad civil del causante y ajusta el reparto a su derecho.", norma: "arts. 14-16 CC", estado: "PENDIENTE", enlace: { sec: "normativa" } });
  for (const a of consumir(/no hereda|no es heredero/)) add({ id: "no-hereda-" + a.slice(0, 16), area: "reparto", tipo: "dato", gravedad: 1, titulo: a.split(":")[0].split(" (")[0] + " no hereda en este reparto", detalle: a, accion: "Si debe recibir algo, hará falta título (testamento, legado o cesión de los herederos).", norma: "arts. 912-958 CC", enlace: { sec: "herencia" } });
  consumir(/Se ha liquidado la sociedad de gananciales/); // hecho normal, no es incidencia
  for (const a of alertasISD) add({ id: "al-" + a.slice(0, 24), area: /legítima|renuncia|menor|reparto|hered/i.test(a) ? "reparto" : "impuestos", tipo: "dato", gravedad: 1, titulo: a.split(/[.:]/)[0].slice(0, 90), detalle: a, accion: "Revísalo antes de presentar.", norma: (a.match(/\(([^)]*(?:art|Ley|CC|STS)[^)]*)\)/) || [])[1] || undefined, enlace: { sec: "impuestos" } });

  // ── Trámites ──
  const T = dgTramites(x, R).filter((t) => !["isd", "plusvalia", "prorroga", "irpf"].includes(t.id));
  const abiertos = T.filter((t) => !dgCerrado(t) && t.limite && !t.informativo).map((t) => ({ t, q: dgDias(h, t.limite) }));
  const venc = abiertos.filter((o) => o.q < 0), sem = abiertos.filter((o) => o.q >= 0 && o.q < 7), mesT = abiertos.filter((o) => o.q >= 7 && o.q <= 30);
  const lista = (L) => L.slice(0, 3).map((o) => o.t.titulo).join("; ") + (L.length > 3 ? ` y ${L.length - 3} más` : "");
  if (venc.length) add({ id: "tr-vencidos", area: "tramites", tipo: "riesgo", gravedad: 2, titulo: `${dgPlural(venc.length, "trámite")} con el plazo vencido`, detalle: lista(venc) + ".", accion: "Hazlos o márcalos como no aplicables si ya no proceden.", enlace: { tramite: venc[0].t.id } });
  if (sem.length) add({ id: "tr-semana", area: "tramites", tipo: "riesgo", gravedad: 2, titulo: `${dgPlural(sem.length, "trámite")} ${sem.length === 1 ? "vence" : "vencen"} esta semana`, detalle: lista(sem) + ".", accion: "Prioriza estos trámites en la agenda de la semana.", enlace: { tramite: sem[0].t.id } });
  if (mesT.length) add({ id: "tr-mes", area: "tramites", tipo: "dato", gravedad: 1, titulo: `${dgPlural(mesT.length, "trámite")} con plazo en los próximos 30 días`, detalle: lista(mesT) + ".", accion: "Repártelos en el calendario del expediente.", enlace: { sec: "tramites", tv: "crono" } });
  const faseAct = (typeof TR_FASES !== "undefined" ? TR_FASES : []).find((f) => T.some((t) => t.fase === f.id && !dgCerrado(t)));
  if (faseAct) { const n = T.filter((t) => t.fase === faseAct.id && !dgCerrado(t)).length; add({ id: "tr-fase", area: "tramites", tipo: "dato", gravedad: 1, titulo: `Fase «${faseAct.nombre}»: ${dgPlural(n, "trámite pendiente", "trámites pendientes")}`, detalle: faseAct.sub + ".", accion: "Cierra los trámites de esta fase antes de pasar a la siguiente.", enlace: { sec: "tramites" } }); }

  // ── Documentación ──
  const falta = (typeof docsNecesarios === "function" ? docsNecesarios(x) : []).filter(([id]) => !x.despacho?.docs?.[id]);
  if (falta.length) { const clave = falta.filter(([id]) => ["defuncion", "ultimas", "testamento", "declaracion"].includes(id)); add({ id: "docs-faltan", area: "docs", tipo: "dato", gravedad: clave.length ? 2 : 1, titulo: `${dgPlural(falta.length, "documento")} por recibir`, detalle: (clave.length ? `Faltan piezas clave: ${clave.map(([, t]) => t.toLowerCase()).join(", ")}. ` : "") + falta.filter(([id]) => !clave.some(([k]) => k === id)).slice(0, 3).map(([, t]) => t).join("; ") + (falta.length - clave.length > 3 ? ` y ${falta.length - clave.length - 3} más` : "") + ".", accion: "Pide al cliente lo que falta con la solicitud preparada y marca cada documento al recibirlo.", enlace: { sec: "despacho", sub: "docs" } }); }
  return dgCerrar(items, x, R);
}
function dgCerrar(items, x, R) {
  const orden = { riesgo: 0, dato: 1, oportunidad: 2 };
  items.sort((a, b) => orden[a.tipo] - orden[b.tipo] || (a.tipo === "oportunidad" ? (b.euros || 0) - (a.euros || 0) : b.gravedad - a.gravedad || (b.euros || 0) - (a.euros || 0)));
  const resta = (L) => L.filter((i) => i.tipo !== "oportunidad").reduce((s, i) => s + (DG_PESO[i.gravedad] || 0), 0);
  const score = Math.max(0, 100 - resta(items));
  const grave = items.some((i) => i.tipo === "riesgo" && i.gravedad === 3);
  const nivel = score >= 80 && !grave ? "bien" : score >= 55 ? "atencion" : "riesgo";
  const areas = DG_AREAS.map(([k, nombre, corto]) => { const L = items.filter((i) => i.area === k && i.tipo !== "oportunidad"); return { k, nombre, corto, score: Math.max(0, 100 - resta(L)), n: L.length, op: items.filter((i) => i.area === k && i.tipo === "oportunidad").length }; });
  return { score, nivel, items, areas, sinCalculo: !R, terr: x.ccaa === "EST" && x.ccaaBienes ? x.ccaaBienes : x.ccaa };
}

// ── Piezas visuales ──
const dgColorNivel = (n) => (n === "bien" ? "var(--green)" : n === "atencion" ? "var(--orange)" : "var(--red)");
const dgNivelDe = (s) => (s >= 80 ? "bien" : s >= 55 ? "atencion" : "riesgo");
function dgRing(score, size, nivel, grosor = 8) {
  const r = 50, c = 2 * Math.PI * r, f = Math.max(0, Math.min(100, score)) / 100;
  return `<svg class="dg-ring" viewBox="0 0 120 120" style="width:${size}px;height:${size}px;--dg-c:${c.toFixed(2)};--dg-col:${dgColorNivel(nivel || dgNivelDe(score))}" role="img" aria-label="Puntuación ${Math.round(score)} sobre 100"><circle class="bg" cx="60" cy="60" r="${r}" fill="none" stroke-width="${grosor}"/><circle class="fg" cx="60" cy="60" r="${r}" fill="none" stroke-width="${grosor}" stroke-linecap="round" stroke-dasharray="${c.toFixed(2)}" stroke-dashoffset="${(c * (1 - f)).toFixed(2)}" transform="rotate(-90 60 60)"/></svg>`;
}
function dgBtn(en, texto = "Ir") {
  if (!en) return "";
  const a = en.sec ? `data-sec="${esc(en.sec)}"${en.sub ? ` data-sub="${esc(en.sub)}"` : ""}${en.tv ? ` data-tv="${esc(en.tv)}"` : ""}` : en.doc ? `data-doc="${esc(en.doc)}"` : en.tramite ? `data-topen="${esc(en.tramite)}"` : en.bien ? `data-editb="${esc(en.bien)}"` : en.persona ? `data-editp="${esc(en.persona)}"` : en.act ? `data-act="${esc(en.act)}"` : "";
  return a ? `<button class="btn sm gray dg-go" ${a}>${esc(texto)}</button>` : "";
}
const DG_ACCION_TXT = { sec: { firma: "Listo para firmar", terceros: "Terceros", impuestos: "Impuestos", estrategia: "Estrategia fiscal", particion: "Partición", herencia: "Herederos y bienes", tramites: "Trámites", despacho: "Encargo y fondos", normativa: "Normativa", documentos: "Documentos" }, doc: "Abrir escrito", tramite: "Ver trámite", bien: "Abrir bien", persona: "Abrir ficha", act: { editar: "Completar datos" } };
function dgTextoBtn(en) { if (!en) return ""; if (en.sec) return DG_ACCION_TXT.sec[en.sec] || "Abrir"; if (en.doc) return DG_ACCION_TXT.doc; if (en.tramite) return DG_ACCION_TXT.tramite; if (en.bien) return DG_ACCION_TXT.bien; if (en.persona) return DG_ACCION_TXT.persona; if (en.act) return DG_ACCION_TXT.act[en.act] || "Abrir"; return "Abrir"; }
const dgChipE = (e) => (e === "PENDIENTE" ? '<span class="tag P">En verificación</span>' : e === "VERIFICADO" ? '<span class="tag V">Verificado</span>' : "");
function dgFila(it, terr) {
  const g = it.tipo === "oportunidad" ? "dg-op" : "g" + it.gravedad;
  const area = DG_AREAS.find((a) => a[0] === it.area);
  return `<div class="dg-row ${it.tipo}"><i class="dg-dot ${g}" aria-hidden="true"></i><div class="dg-t"><b>${esc(it.titulo)}</b><small>${esc(it.detalle || "")}</small><div class="dg-acc"><span class="dg-arrow" aria-hidden="true">→</span>${esc(it.accion || "")}</div><div class="dg-meta">${it.euros ? `<span class="dg-eur ${it.tipo === "oportunidad" ? "dg-op" : ""}">${it.tipo === "oportunidad" ? "+" : ""}${eur0(it.euros)}</span>` : ""}${area ? `<span>${esc(area.nombre)}</span>` : ""}${it.norma ? `<span class="dg-norma">${typeof linkNorma === "function" ? it.norma.split(" · ").map((n) => linkNorma(n, terr)).join(" · ") : esc(it.norma)}</span>` : ""}${it.norma ? dgChipE(it.estado) : ""}</div></div><div class="dg-go-w">${dgBtn(it.enlace, dgTextoBtn(it.enlace))}</div></div>`;
}
function dgVeredicto(D) {
  const ries = D.items.filter((i) => i.tipo === "riesgo"), top = ries[0];
  if (D.sinCalculo) return "Completa fecha, territorio, una persona y un bien para diagnosticar el expediente.";
  if (D.nivel === "bien") return ries.length ? `Sin urgencias. Lo más relevante: «${top.titulo}».` : "Nada urgente. Revisa las oportunidades y completa los datos pendientes.";
  if (D.nivel === "atencion") return top ? `Conviene resolver algunos puntos antes de seguir. El primero: «${top.titulo}».` : "Conviene completar los datos pendientes antes de seguir.";
  return top ? `Hay riesgos que pueden costar dinero al cliente. El primero: «${top.titulo}».` : "Hay demasiados datos sin completar para fiarse del cálculo.";
}

// ── Pestaña completa ──
function tDiagnostico(x, R) {
  const D = diagnostico(x, R);
  const ries = D.items.filter((i) => i.tipo === "riesgo"), ops = D.items.filter((i) => i.tipo === "oportunidad"), datos = D.items.filter((i) => i.tipo === "dato");
  const euroR = ries.reduce((s, i) => s + (i.euros || 0), 0), euroO = ops.reduce((s, i) => s + (i.euros || 0), 0);
  const hero = `<div class="card dg-hero nivel-${D.nivel}">
    <div class="dg-hero-ring">${dgRing(D.score, 148, D.nivel, 7)}<div class="dg-score"><b class="num">${Math.round(D.score)}</b><small>de 100</small></div></div>
    <div class="dg-hero-t"><div class="k">Diagnóstico del expediente</div><h2>${D.sinCalculo ? "Sin calcular" : DG_NIVEL[D.nivel]}</h2><p>${esc(dgVeredicto(D))}</p>
      <div class="dg-hero-meta"><span><i class="dg-dot g3"></i>${dgPlural(ries.length, "riesgo")}${euroR ? ` · ${eur0(euroR)} en juego` : ""}</span><span><i class="dg-dot dg-op"></i>${dgPlural(ops.length, "oportunidad", "oportunidades")}${euroO ? ` · ${eur0(euroO)} de ahorro fiscal hoy` : ""}</span><span><i class="dg-dot g1"></i>${dgPlural(datos.length, "dato por completar", "datos por completar")}</span></div></div>
    <div class="dg-hero-acts">${R ? `<button class="btn sm gray" data-act="informePdf">${I.dl}Informe en PDF</button>` : `<button class="btn sm" data-act="editar">Completar datos</button>`}<span class="caption">Revisado hoy, ${fechaCorta(dgHoy())}</span></div>
  </div>`;
  const tiles = `<div class="dg-areas">${D.areas.map((a) => `<div class="card dg-area nivel-${dgNivelDe(a.score)} ${D.sinCalculo && a.k !== "datos" ? "off" : ""}">${dgRing(D.sinCalculo && a.k !== "datos" ? 0 : a.score, 44, dgNivelDe(a.score), 10)}<div><b>${esc(a.corto)}</b><small>${D.sinCalculo && a.k !== "datos" ? "Sin datos" : a.n ? dgPlural(a.n, "aviso") + (a.op ? ` · ${a.op} op.` : "") : a.op ? dgPlural(a.op, "oportunidad", "oportunidades") : "Correcto"}</small></div></div>`).join("")}</div>`;
  const grupo = (tit, L, vacio) => `<div class="sectitle flex"><b>${tit}</b><span>${L.length}</span></div>${L.length ? `<div class="group dg-list">${L.map((it) => dgFila(it, D.terr)).join("")}</div>` : `<p class="caption dg-vacio">${vacio}</p>`}`;
  const cuerpo = !ries.length && !datos.length ? `<div class="card empty dg-empty" style="margin-top:14px"><b>Nada que corregir hoy</b>Los plazos, los datos, el reparto y la documentación están en orden.${ops.length ? " Quedan oportunidades por valorar." : ""}</div>${ops.length ? grupo("Oportunidades", ops, "") : ""}` : `${grupo("Riesgos", ries, "Sin riesgos detectados.")}${grupo("Oportunidades", ops, D.sinCalculo ? "Las oportunidades aparecen cuando el expediente se puede calcular." : "Sin oportunidades adicionales con los datos actuales.")}${grupo("Datos por completar", datos, "Todos los datos necesarios están recogidos.")}`;
  return `<div class="dg">${hero}${tiles}${cuerpo}<p class="foot-note">El diagnóstico se genera con las reglas del motor y los datos del expediente. Señala lo que conviene revisar; la decisión es del abogado.</p></div>`;
}

// ── Tarjeta compacta para el Resumen ──
function dgResumen(x, R) {
  const D = diagnostico(x, R);
  const top = D.items.filter((i) => i.tipo !== "oportunidad").slice(0, 3);
  const L = top.length ? top : D.items.slice(0, 3);
  return `<div class="card dg-mini nivel-${D.nivel}"><div class="card-h"><div><div class="k">Diagnóstico</div><h3>${D.sinCalculo ? "Sin calcular" : DG_NIVEL[D.nivel]} · ${Math.round(D.score)} de 100</h3></div><button class="link" data-sec="diagnostico">Ver diagnóstico ›</button></div>
    <div class="dg-mini-b"><div class="dg-hero-ring sm">${dgRing(D.score, 84, D.nivel, 8)}<div class="dg-score"><b class="num">${Math.round(D.score)}</b></div></div>
    <div class="dg-mini-l">${L.length ? L.map((it) => `<button class="dg-mini-r" data-sec="diagnostico"><i class="dg-dot ${it.tipo === "oportunidad" ? "dg-op" : "g" + it.gravedad}"></i><span><b>${esc(it.titulo)}</b>${it.euros ? `<small>${it.tipo === "oportunidad" ? "+" : ""}${eur0(it.euros)}</small>` : ""}</span></button>`).join("") : `<p class="caption" style="margin:6px 0">Nada que corregir hoy.</p>`}</div></div></div>`;
}

// ── Bloques para el informe en PDF (pdf.js) ──
function dgParaInforme(x, R) {
  const D = diagnostico(x, R), bl = [];
  const linea = (it) => `${it.titulo}. ${it.detalle || ""} Qué hacer: ${it.accion || "—"}${it.euros ? ` (${eur0(it.euros)})` : ""}${it.norma ? ` [${it.norma}${it.estado === "PENDIENTE" ? " · en verificación" : ""}]` : ""}`;
  bl.push({ tipo: "h", texto: `Diagnóstico del expediente: ${D.sinCalculo ? "sin calcular" : DG_NIVEL[D.nivel].toLowerCase()}, ${Math.round(D.score)} de 100` });
  bl.push({ tipo: "p", texto: dgVeredicto(D) + " " + D.areas.map((a) => `${a.nombre} ${Math.round(a.score)}`).join(" · ") + "." });
  const ries = D.items.filter((i) => i.tipo === "riesgo"), ops = D.items.filter((i) => i.tipo === "oportunidad"), datos = D.items.filter((i) => i.tipo === "dato");
  if (ries.length) { bl.push({ tipo: "p", texto: "Riesgos" }); bl.push({ tipo: "lista", items: ries.map(linea) }); }
  if (ops.length) { bl.push({ tipo: "p", texto: "Oportunidades" }); bl.push({ tipo: "lista", items: ops.map(linea) }); }
  if (datos.length) { bl.push({ tipo: "p", texto: "Datos por completar" }); bl.push({ tipo: "lista", items: datos.map(linea) }); }
  if (!ries.length && !datos.length) bl.push({ tipo: "p", texto: "Nada que corregir a la fecha del diagnóstico." });
  bl.push({ tipo: "nota", texto: `Diagnóstico generado el ${fechaLarga(dgHoy())} con las reglas del motor y los datos del expediente. Señala lo que conviene revisar; la decisión es del abogado.` });
  return bl;
}

// ───────────────────── Control de calidad 07-10-2026 · datos jurídicos que el expediente pasa al motor ─────────────────────
// C2 · ¿Se presenta en plazo? Si el abogado no lo ha fijado (interruptor de Impuestos: x.enPlazoManual, o un «fuera de plazo» guardado antes)
// y el Impuesto no consta presentado, se deriva de las fechas: pasado el plazo de seis meses (doce con la prórroga concedida, marcada en
// Trámites) se calcula fuera de plazo, con recargo y sin las bonificaciones que exigen presentar a tiempo (arts. 67-68 RD 1629/1991; art. 27 LGT).
function dgPlazoInfo(x) {
  const manual = x.enPlazoManual === true || x.enPlazo === false;
  const presentado = !!(x.tramites && x.tramites.isd && x.tramites.isd.estado === "hecho");
  const prorroga = !!(x.tramites && x.tramites.prorroga && x.tramites.prorroga.estado === "hecho");
  const plazo = x.fecha && typeof plazoPresentacionISD === "function" ? plazoPresentacionISD(x.fecha, { hoy: dgHoy(), prorroga, ccaa: x.ccaa, ine: x.muniPlazos || "" }) : null;
  if (manual || presentado || !plazo || x.proyeccion) return { enPlazo: x.enPlazo !== false, auto: false, plazo, presentado, prorroga };
  return { enPlazo: !plazo.fueraDePlazo, auto: true, plazo, presentado, prorroga };
}
function enPlazoExp(x) { return dgPlazoInfo(x).enPlazo; }
// Campos jurídicos que casoMotor (logic.js) añade al caso del motor: plazo derivado, fecha de referencia para el recargo, prórroga,
// vecindad civil (I6), isla (Baleares) y conmutación del usufructo catalán (art. 442-5 CCCat).
function casoMotorJur(x) {
  const P = dgPlazoInfo(x);
  return { enPlazo: P.enPlazo, fechaReferencia: P.presentado || x.proyeccion ? undefined : dgHoy(), prorrogaISD: P.prorroga, vecindadCivil: x.vecindadCivil || undefined, isla: x.isla || undefined, conmutacionCat: x.conmutacionCat === true,
    // Auditoría civil 10-10-2026: acrecimiento con cuotas (C-2) y ley sucesoria con elemento internacional (D-1, Reglamento (UE) 650/2012)
    acrecer: x.acrecer || undefined, residenciaExtranjero: x.ccaa === "EST" || undefined, nacionalidadExtranjera: !!(x.situ && x.situ.nacionalidadExtranjera) || undefined, professioIuris: x.professioIuris || undefined };
}
// Aviso rojo cuando el reparto legal no se puede calcular (vecindad foral no modelada): Impuestos, Herederos y Resumen
function bloqueoRepartoHTML(x, R) {
  const B = R && R.isd && R.isd.bloqueo; if (!B) return "";
  return `<div class="infobar" role="alert" style="margin:0 0 14px;box-shadow:inset 3px 0 0 var(--red),var(--sh-1)"><span class="ico red">${I.info}</span><span><b>${esc(B.titulo)}.</b> ${esc(B.motivo)} ${esc(B.accion)} <small>${esc(B.norma)} · PENDIENTE</small> <button class="link" data-sec="herencia">Vecindad civil ›</button></span></div>`;
}
// Aviso de plazo derivado para la opción «Se presentará dentro de plazo» de Impuestos
function dgPlazoHint(x, R) {
  const P = dgPlazoInfo(x);
  if (P.auto && !P.enPlazo) return `Calculado según las fechas: el plazo venció el ${fechaCorta(P.plazo.limite)}${P.prorroga ? " (con prórroga)" : " y no consta prórroga"}. Si se presentó a tiempo, actívalo.${R && R.isd.recargo && R.isd.recargo.importe ? ` Recargo estimado a hoy: ${eur(R.isd.recargo.importe)} (${R.isd.recargo.etiqueta}).` : ""}`;
  if (P.auto) return `Calculado según las fechas: el plazo acaba el ${fechaCorta(P.plazo.limite)}.`;
  return P.presentado ? "Impuesto marcado como presentado en Trámites." : "Fijado a mano en el expediente.";
}
